version: '3.7'

# объявляем какие сервисы буду запускаться (в данном случае только тесты)
services:
  # название тестов
  regretion:
    # с чего будет собираться образ
    image: python:3.12.0a4-alpine3.17
    # если не находит image локально, то собирай
    build:
      # из текущей директории
      context: .
      # из докер файла в этой директории по инструкциям файла
      dockerfile: Dockerfile
    # связь контейнера (виртуальной среды) с репозиторием
    volumes:
      # прокидываем всю текущую директорию внутрь контейнера в папку /usr/workspace (содержимое проекта скопирует в докер контейнер)
      - ./:/usr/workspace
    # команда которая ответчает за запуск
    # /bin/sh оболчка откуда запускают (shell), -sv выводит принты, создает каталог для allure отчетов
    command: /bin/sh -c "ls -la && pytest -sv  --alluredir=allure-results"
    # указываем рабочий каталог (навсякий)
    working_dir: /usr/workspace
    environment:
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}
